name: Python Linting and Formatting  

on:  
  push:  
    branches:  
      - main  
  pull_request:  
    branches:  
      - main  

jobs:  
  lint-and-format:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Vérifier le code  
        uses: actions/checkout@v2  

      - name: Configurer Python  
        uses: actions/setup-python@v2  
        with:  
          python-version: '3.10'  

      - name: Installer les dépendances  
        run: |  
          python -m pip install --upgrade pip  
          pip install black ruff  # Installe Black et Ruff  

      - name: Vérifier le formatage avec Black  
        run: |  
          black --check .  # Vérifie le formatage  

      - name: Vérifier la qualité du code avec Ruff  
        run: |  
          ruff check .  # Vérifie la qualité du code  